### ISSUE TITLE
How to select which GPU to use?

### ISSUE THREAD

**Issue by ghmchen** [shouxieai/infer#11]
I have two GPUs. It would be great if I can point to which GPU  to use by "auto yolo = yolo::load(modelpath, modelType, gpuID); " I am trying to modify codes by add "SetDevice(const int gpuID)" to the function construct() at infer.cn. But without sucess. Any sugestion? Thanks.

**Comment by shouxieai** [comment]
You can use the cudaSetDevice function before loading the model.

**Comment by ghmchen** [comment]
I will try it. Thanks.
