### ISSUE TITLE
怎么写一个 CMakeLists.txt 而不是用 kiwi？

### ISSUE THREAD

**Issue by deepConnectionism** [shouxieai/infer#19]
怎么写一个 CMakeLists.txt 而不是用 kiwi？假设我已经装好 所需要的库。

**Comment by jhqxxx** [comment]
cmake_minimum_required(VERSION 3.9)

project(infer)

enable_language(CUDA)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CUDA_STANDARD 11)

aux_source_directory(src SRC_LIST)
include_directories(src)

find_package(OpenCV)
include_directories(${OpenCV_INCLUDE_DIRS})
find_package(CUDA REQUIRED)
include_directories(${CUDA_INCLUDE_DIRS})


set(TensorRT_ROOT_DIR /usr/local/TensorRT-8.6.1.6)
file(GLOB TensorRT_LIBRARY_DIR ${TensorRT_ROOT_DIR}/lib/*.so)
set(TensorRT_INCLUDE_DIR ${TensorRT_ROOT_DIR}/include)
include_directories(${TensorRT_INCLUDE_DIR})

add_executable(${PROJECT_NAME} ${SRC_LIST})
target_link_libraries(${PROJECT_NAME} ${TensorRT_LIBRARY_DIR} ${CUDA_LIBRARIES} ${OpenCV_LIBS})

**Comment by deepConnectionism** [comment]
https://www.cnblogs.com/odesey/p/18399373

@jhqxxx  感谢 我在docker 里面成功实现了
