### ISSUE TITLE
老师好，yolov8官方的检查模型输出是1 84 8400， 需要手动转成1 84 8400后，再转换模型推理吗？

### ISSUE THREAD

**Issue by xinsuinizhuan** [shouxieai/infer#3]
我在代码里面，没看到transpose操作，是需要提前自己手动转好吗？

**Comment by shouxieai** [comment]
不需要在代码里面修改。workspace/v8trans.py可以直接在onnx里面增加

**Comment by shouxieai** [comment]
比如执行
python workspace/v8trans.py workspace/yolov8n.onnx
它会保存一个名字叫yolov8n.transd.onnx文件，是添加了transpose节点的

**Comment by xinsuinizhuan** [comment]
OK！
