### ISSUE TITLE
多卡支持

### ISSUE THREAD

**Issue by KkemChen** [shouxieai/infer#32]
假设我现在想要尝试支持多卡，是不是在 infer.cu:251 的__native_engine_context::construct里面新增设备id参数，然后在createInferRuntime之前 先调用cudaSetDevice(device_id)，就可以指定到某块具体的显卡上？

**Comment by wawatt** [comment]
> 假设我现在想要尝试支持多卡，是不是在 infer.cu:251 的__native_engine_context::construct里面新增设备id参数，然后在createInferRuntime之前 先调用cudaSetDevice(device_id)，就可以指定到某块具体的显卡上？

如何实现多gpu？
