### ISSUE TITLE
During preprocessing image, error reported in "warp_affine_bilinear_and_normalize_plane_kernel"

### ISSUE THREAD

**Issue by ghmchen** [shouxieai/infer#6]
I get error message _:"[yolo.cu:339]: CUDA Runtime error≡ƒÆÑ cudaPeekAtLastError() # too many resources requested for launch, code = cudaErrorLaunchOutOfResources [ 701 ]"_
It points to the Kernal function: _checkKernel(warp_affine_bilinear_and_normalize_plane_kernel << <grid, block, 0, stream >> > (src, src_line_size, src_width, src_height, dst, dst_width, dst_height, const_value,	matrix_2_3, norm));_
There is no problem with the kernal function at simple_yolo.cu (The previous version).
![Capture](https://user-images.githubusercontent.com/46462888/223575970-4a32605c-e203-489e-a9f9-16d64bd10599.JPG)

**Comment by shouxieai** [comment]
This may be caused by your device being weak and limiting the blockDim to less than 1024. This can be queried via deviceQuery program. You can change 32 to 16 and 31 to 15 in either gridDim or blockDim to reduce the resource requirements.

**Comment by ghmchen** [comment]
Hi Shouxieal, Yes, my laptop video card is weak. after modifing the blockDim as you suggested, it works like a charm!
