### ISSUE TITLE
compile infer on jetson

### ISSUE THREAD

**Issue by Mason1992-Git** [shouxieai/infer#8]
environment：cuda10.2 opencv4.2 tensorrt7.x
use CmakeLists.txt  compile,cmakelists contents :
cmake_minimum_required(VERSION 3.16)
PROJECT(pro VERSION 1.0.0 LANGUAGES C CXX CUDA)
option(CUDA_USE_STATIC_CUDA_RUNTIME OFF)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_BUILD_TYPE Debug)
set(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/workspace)
set(CUDA_GEN_CODE "-gencode=arch=compute_75,code=sm_75")
if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
set(CMAKE_CUDA_ARCHITECTURES 70 75 80)
endif(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
set(OpenCV_DIR  "/usr/include/opencv4/")
set(CUDA_TOOLKIT_ROOT_DIR "/usr/local/cuda-10.2")
set(CUDNN_DIR  "/usr/include/aarch64-linux-gnu")
set(TENSORRT_DIR "/usr/include/aarch64-linux-gnu")

find_package(CUDA REQUIRED)
find_package(OpenCV)

include_directories(
    ${PROJECT_SOURCE_DIR}/src
    ${OpenCV_DIR}/include
    ${OpenCV_INCLUDE_DIRS}
    ${CUDA_TOOLKIT_ROOT_DIR}/include
    ${TENSORRT_DIR}/include
    ${TENSORRT_DIR}
    ${CUDNN_DIR}/include
    ${CUDNN_DIR}
)
link_directories(
    ${TENSORRT_DIR}/lib
    ${CUDA_TOOLKIT_ROOT_DIR}/lib
    ${CUDNN_DIR}
    ${OpenCV_DIR}/x64/vc15/lib
)
set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -O0 -Wfatal-errors -pthread -w -g")
set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -std=c++11 -O0 -Xcompiler -fPIC -g -w ${CUDA_GEN_CODE}")
file(GLOB_RECURSE cpp_srcs ${PROJECT_SOURCE_DIR}/src/*.cpp)
file(GLOB_RECURSE cuda_srcs ${PROJECT_SOURCE_DIR}/src/*.cu)
cuda_add_library(plugin_list SHARED ${cuda_srcs})
target_link_libraries(plugin_list nvinfer nvinfer_plugin nvonnxparser)
target_link_libraries(plugin_list cuda cublas cudart cudnn)
target_link_libraries(plugin_list stdc++ dl)
target_link_libraries(plugin_list ${OpenCV_LIBS})
add_executable(pro ${cpp_srcs})
target_link_libraries(pro nvinfer nvinfer_plugin nvonnxparser)
target_link_libraries(pro cuda cublas cudart cudnn)
target_link_libraries(pro stdc++ dl)
target_link_libraries(pro  plugin_list)
target_link_libraries(pro ${OpenCV_LIBS})

but errors occur when make ：
![image](https://user-images.githubusercontent.com/79744902/225533497-d5369df3-18c3-47fc-a277-b6e4ff20042e.png)
 
 error: argument of type "void *const *" is incompatible with parameter of type "void **"

1 error detected in the compilation of "/tmp/tmpxft_00000d3a_00000000-6_infer.cpp1.ii".
CMake Error at plugin_list_generated_infer.cu.o.Debug.cmake:280 (message):
  Error generating file
  /media/tye/7b97c143-3564-430b-838e-6051e9005553/infer-main/build/CMakeFiles/plugin_list.dir/src/./plugin_list_generated_infer.cu.o

CMakeFiles/plugin_list.dir/build.make:75: recipe for target 'CMakeFiles/plugin_list.dir/src/plugin_list_generated_infer.cu.o' failed

what's the reason how to solve it?thanks!

**Comment by shouxieai** [comment]
I have updated the issue. Thanks for the feedback!

**Comment by Mason1992-Git** [comment]
thanks !Gold Du.got it!
